name: Exercitium1314
version: '0.1.0.0'
synopsis: Problemas de Exercitium (curso 2013-14)
description: |
  Ejercicios de programación funcional con Haskell propuestos en el blog
  Exercitium durante el curso 2013-14. 
category: Excercises
author: Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright: Jose A. Alonso
license: GPL-3
github: jaalonso/Exercitium1314
extra-source-files:
- README.org
dependencies:
- QuickCheck
- array
- base >=4.7 && <5
- doctest
- primes
library:
  source-dirs: src
  ghc-options: -Wall
tests:
  doctests:
    main: Doctest.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
    - doctest-discover
