name: Exercitium1
version: '0.1.0.0'
synopsis: Problemas de Exercitium (Volumen 1)
description: |
  Durante el curso 2013-14 se creó el blog
  <http://www.glc.us.es/~jalonso/exercitium Exercitium>
  como complemento del curso de
  <http://www.cs.us.es/~jalonso/cursos/i1m-13/ Informática>
  de 1º del Grado de Matemáticas de la Universidad de Sevilla.

  El objetivo de
  <http://www.glc.us.es/~jalonso/exercitium Exercitium>
  es plantear diariamente un problema para que los alumnos pudieran practicar y
  escribir distintas soluciones en los comentarios.

  Esta librería es una recopilación de los ejercicios propuestos en
  <http://www.glc.us.es/~jalonso/exercitium Exercitium>
  durante el curso 2013-14.

author: Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
category: Education, Learning Haskell, Math, Teaching
copyright: Jose A. Alonso
license: GPL-3
github: jaalonso/Exercitium1314
extra-source-files:
- README.org
dependencies:
- QuickCheck
- array
- base >=4.7 && <5
- primes
library:
  source-dirs: src
  ghc-options: -Wall -fno-warn-type-defaults
tests:
  doctests:
    main: Main.hs
    source-dirs: test
    ghc-options: -threaded
    dependencies:
    - Glob
    - doctest
