name: Exercitium1314
version: '0.1.0.0'
synopsis: Problemas de Exercitium (curso 2013-14)
description: ! 'Ejercicios de programación funcional con Haskell propuestos en el blog Exercitium durante el curso 2013-14.' 
author: Jose A. Alonso
maintainer: JoseA.Alonso@gmail.com
copyright: Jose A. Alonso
license: BSD3
github: jaalonso/Exercitium1314
extra-source-files:
- README.org
dependencies:
- QuickCheck >=2.8.1
- array
- primes
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Iguales_al_siguiente
  - Ordenados_por_maximo
  - Bandera_tricolor
  - ElementosMinimales
  - Mastermind
  - Primos_consecutivos_con_media_capicua
  - Anagramas
  - Primos_equidistantes
  - Suma_si_todos_justos
  - Matriz_Toeplitz
  dependencies:
  - base >=4.7 && <5
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Exercitium1314
    - base
    - hspec
